#!/bin/bash

sudo yum install -y git
sudo useradd jenkins
git clone https://github.com/bob-crutchley/python-systemd-http-server
cd python-systemd-http-server
sudo make install
sudo systemctl start python-systemd-http-server
sudo systemctl enable python-systemd-http-server
touch complete.txt
